# Generated by Django 2.0.5 on 2018-10-19 07:11

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phno', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, null=True, unique=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('date', models.DateField()),
                ('citations', models.CharField(max_length=400)),
                ('paper_journal', models.CharField(choices=[('PR', 'Paper'), ('JO', 'Journal')], max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minerva_core.Person')),
            ],
        ),
    ]
