# Generated by Django 2.1.2 on 2018-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerva_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='paper_pdf',
            field=models.FileField(default='', upload_to='papers/'),
            preserve_default=False,
        ),
    ]
