# Generated by Django 2.1.2 on 2018-10-21 09:55

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('minerva_core', '0003_auto_20181021_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(to='minerva_core.Person', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citations',
            field=models.CharField(max_length=400, verbose_name='Citations'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=isbn_field.fields.ISBNField(max_length=28, null=True, unique=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN Number'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paper_journal',
            field=models.CharField(choices=[('PR', 'Paper'), ('JO', 'Journal')], max_length=2, verbose_name='Type Of Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Publication Title'),
        ),
    ]
